ERROR 2024-08-22 21:41:08,505 log Internal Server Error: /
Traceback (most recent call last):
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sargent/spite/blog/views.py", line 12, in home
    return render(request, 'blog/home.html',context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 481, in parse
    raise self.error(token, e)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 597, in compile_filter
    return FilterExpression(token, self)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '-id' from 'post-id'
ERROR 2024-08-22 21:47:38,463 log Internal Server Error: /admin/blog/post/5/change/
Traceback (most recent call last):
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: blog_post.description

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/contrib/admin/options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1948, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1824, in _changeform_view
    obj = self.get_object(request, unquote(object_id), to_field)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/contrib/admin/options.py", line 894, in get_object
    return queryset.get(**{field.name: object_id})
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: blog_post.description
ERROR 2024-08-22 21:47:39,987 log Internal Server Error: /admin/blog/post/5/change/
Traceback (most recent call last):
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: blog_post.description

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/contrib/admin/options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1948, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1824, in _changeform_view
    obj = self.get_object(request, unquote(object_id), to_field)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/contrib/admin/options.py", line 894, in get_object
    return queryset.get(**{field.name: object_id})
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: blog_post.description
ERROR 2024-08-22 21:47:44,143 log Internal Server Error: /
Traceback (most recent call last):
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: blog_post.description

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sargent/spite/blog/views.py", line 12, in home
    return render(request, 'blog/home.html',context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/context.py", line 254, in bind_template
    context = processor(self.request)
  File "/home/sargent/spite/spite/context_processors.py", line 7, in load_posts
    'spite' : len(posts)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: blog_post.description
ERROR 2024-08-22 21:48:11,804 log Internal Server Error: /
Traceback (most recent call last):
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: blog_post.description

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sargent/spite/blog/views.py", line 12, in home
    return render(request, 'blog/home.html',context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/template/context.py", line 254, in bind_template
    context = processor(self.request)
  File "/home/sargent/spite/spite/context_processors.py", line 7, in load_posts
    'spite' : len(posts)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: blog_post.description
ERROR 2024-08-22 22:24:46,787 log Internal Server Error: /
Traceback (most recent call last):
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sargent/spite/blog/views.py", line 9, in home
    return render(request, 'blog/home.html',context)
NameError: name 'context' is not defined
ERROR 2024-08-22 22:24:48,327 log Internal Server Error: /
Traceback (most recent call last):
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sargent/spite/.spite/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sargent/spite/blog/views.py", line 9, in home
    return render(request, 'blog/home.html',context)
NameError: name 'context' is not defined
